### ISSUE TITLE
Helm crashing Carla (JackTemporaryException error)

### ISSUE THREAD

**Issue by asbaklm** [mtytel/helm#62]
When hosting Helm in Carla (latest git version) on a LM 17.3 64Bit system w. Cinnamon desktop, Helm VST and Helm LV2 (latest git versions) tend to crash Carla when GUI's are opened and closed with a "JackTemporaryException" showing up on the terminal from which Carla was launched.

A recent git version of jack2 is installed. I haven't yet experienced similar issues with other synth plugins running in Carla, only Helm seems to be affected.

Carla assertion failure: "fLatencyIndex == static_cast<int32_t>(j)" in file CarlaPluginLV2.cpp, line 2215
Segmentation fault
audio@I7 ~ $ JackPosixSemaphore::TimedWait err = Connection timed out
JackFreewheelDriver::ProcessSync: SuspendRefNum error
JackAudioDriver::ProcessGraphSync: ProcessWriteSlaves error, engine may now behave abnormally!!
JackPosixProcessSync::LockedTimedWait error usec = 10664 err = Connection timed out
JackEngine::ClientCloseAux wait error ref = 2
Cannot write socket fd = 20 err = Broken pipe
CheckRes error
Could not write notification
ClientNotify fails name = Carla notification = 1 val1 = 0 val2 = 0
JackPosixSemaphore::TimedWait err = Connection timed out
JackFreewheelDriver::ProcessSync: SuspendRefNum error
JackAudioDriver::ProcessGraphSync: ProcessWriteSlaves error, engine may now behave abnormally!!
Unknown error...
terminate called after throwing an instance of 'Jack::JackTemporaryException'
  what():

**Comment by mtytel** [comment]
Thanks for letting me know!
I fixed a plugin crash that would happen when closing Helm. I'm not sure if this is what you're seeing, but it sounds like it's the same issue so should be fixed now. Away from my linux box right now so will test this another time.

**Comment by asbaklm** [comment]
Awesome Matt! :+1: 

I just compiled & installed the latest LV2 and VST versions, the above mentioned problem with Jack doesn't appear anymore so I think you nailed it.

Here's what I'm getting now.

When using Carla-git as a host:
---------------------------------------

LV2 version status:
Synth plays.
GUI issue persists, GUI is basically unusable because of previously mentioned issues.

Helm VST version status:
Synth plays.
Helm VST GUI will not load in Carla, or it only loads very occasionally, or, it crashes Carla. Even when the GUI loads, the Helm panel is oversized inside the GUI framework making it unusable.

Carla logs for Helm VST
audioMasterAutomate called from unknown source
ScopedPluginAction(0) - blocking START
ScopedPluginAction(0) - blocking DONE
Segmentation fault


Using Muse-git as a host:
--------------------------------
First attempt
Helm LV2 plugin loads in Muse3
Helm LV2 GUI plugin crashes Muse3 (could have been a Muse issue, not sure).

Lv2Gtk2Helper: dlerror = (null)
Lv2Gtk2Helper: dlerror (libgtk-x11-2.0.so) = (null)
Lv2Gtk2Helper: dlerror (libgtkmm-2.4.so) = (null)
Segmentation fault

On second attempt, LV2 plugin loads in Muse3 and gui loads.
The Helm LV2 GUI Frame is always oversized.
GUI oversize problem persists. By dragging the Helm GUI between monitors the Helm panel inside the LV2 GUI frame resizes itself (it seems to jump between the 'correct usable size' and  oversized depending on how far it was dragged between the monitors.)


Helm VST Plugin in Muse3
Helm VST plugin loads in Muse3
Helm VST GUI loads in Muse3 (loads more reliably than in Carla)
GUI Frame appears to be the correct size but the Helm Panel is oversized inside the GUI frame, making it unusable.

**Comment by mtytel** [comment]
Well after a bunch of testing I can't reproduce any of this..
Not sure what's going on but it all sounds related, maybe I should get my hands on some more testing machines..

**Comment by mtytel** [comment]
Thanks for the thorough description. :D

**Comment by asbaklm** [comment]
yw! It's an awesome little synth. :)
